FROM nginx:latest
MAINTAINER HUI XU <gw.iuhux@gmail.com>

VOLUME /etc/nginx

# Change Nginx config here...
#RUN rm /etc/nginx/conf.d/default.conf
#ADD ./default.conf /etc/nginx/conf.d/

#CMD ["nginx", "-g", "daemon off;"]
